# Build stage
FROM golang:1.26.6-alpine AS builder

WORKDIR /app

# Install build dependencies
RUN apk update && apk add --no-cache curl git vim make

RUN cd /opt && git clone https://github.com/go-delve/delve && cd delve && go install github.com/go-delve/delve/cmd/dlv

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 8080

# Run the application
CMD ["./bin/api"]

