apiVersion: v1
kind: Service
metadata:
  name: go-k8s-service      # A stable service name (DNS address)
spec:
  type: NodePort            # Makes your app accessible outside the cluster
  selector:
    app: micro-app-boilerplate-go         # Match Pods with this label
  ports:
    - port: 8080            # Service port (cluster-wide port)
      nodePort: 30080       # Port on each Kubernetes node
